const SUPABASE_URL="https://pbhaqatyrjxnaithmowe.supabase.co";
const SUPABASE_KEY="sb_publishable_rNA8ggZxU1g_UhfCTGG96Q_MeCkQNjP";
const supabase=window.supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
const chat=document.querySelector("#chat"),form=document.querySelector("#composer"),input=document.querySelector("#input"),send=document.querySelector("#send"),status=document.querySelector("#status");
let userId=null,conversationId=null,memory=[];
function addMessage(role,text){document.querySelector(".welcome")?.remove();const row=document.createElement("div");row.className="msg "+role;const bubble=document.createElement("div");bubble.className="bubble";bubble.textContent=text;row.appendChild(bubble);chat.appendChild(row);chat.scrollTop=chat.scrollHeight}
function clean(s){return s.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"")}
function findMemories(q){const words=clean(q).split(/\W+/).filter(w=>w.length>3);return memory.filter(m=>words.some(w=>clean(m.content).includes(w))).slice(0,4)}
function rememberFrom(text){const patterns=[[/me llamo ([^.!?]+)/i,"nombre","fact"],[/mi nombre es ([^.!?]+)/i,"nombre","fact"],[/prefiero ([^.!?]+)/i,"preferencia","preference"],[/me gusta ([^.!?]+)/i,"gustos","preference"]];return patterns.flatMap(([re,key,type])=>{const m=text.match(re);return m?[{memory_key:key,content:m[1].trim(),memory_type:type,importance:.8,source:"conversation"}]:[]})}
function generate(q){const refs=findMemories(q),c=clean(q);if(/^(hola|hey|buenas|saludos)\b/.test(c))return"Hola. Soy Fénix. Estoy conectado a mi memoria y puedo usar el contexto de nuestras conversaciones.";if(c.includes("quien eres")||c.includes("que eres"))return"Soy Fénix, un sistema experimental centrado en contexto y memoria persistente. Esta versión todavía está creciendo, pero ya puedo conservar información útil y recuperarla cuando sea relevante.";if(c.includes("que recuerdas")||c.includes("que sabes de mi"))return refs.length?"Recuerdo esto relacionado con lo que acabas de decir:\n\n"+refs.map(x=>"• "+x.content).join("\n"):"Todavía no tengo recuerdos relevantes guardados para esa pregunta.";if(refs.length)return"Entiendo. Estoy usando parte de lo que recuerdo para responder con contexto:\n\n"+refs.map(x=>"• "+x.content).join("\n")+"\n\nSobre tu mensaje: "+q;return"He procesado tu mensaje con el núcleo contextual de Fénix. Todavía no tengo un modelo generativo conectado en esta versión, así que prefiero no inventar una respuesta y llamarla inteligencia. Puedo conservar este contexto y usarlo después."}
async function ensureAuth(){let {data}=await supabase.auth.getSession();if(!data.session){const r=await supabase.auth.signInAnonymously();if(r.error)throw new Error("Activa Anonymous Sign-Ins en Supabase Auth.");data={session:r.data.session}}userId=data.session.user.id}
async function loadMemory(){const {data,error}=await supabase.from("fenix_memory").select("*").order("updated_at",{ascending:false}).limit(80);if(error)throw error;memory=data||[]}
async function ensureConversation(){const {data,error}=await supabase.from("fenix_conversations").insert({user_id:userId,title:"Nueva conversación"}).select("id").single();if(error)throw error;conversationId=data.id}
async function saveMessage(role,content){const {error}=await supabase.from("fenix_messages").insert({conversation_id:conversationId,user_id:userId,role,content});if(error)console.error(error)}
async function saveMemories(items){for(const item of items){const {error}=await supabase.from("fenix_memory").insert({...item,user_id:userId});if(error)console.error(error)}if(items.length)await loadMemory()}
async function boot(){try{await ensureAuth();await loadMemory();await ensureConversation();status.textContent="online";status.classList.add("ready")}catch(e){console.error(e);status.textContent="configuración pendiente"}}
form.addEventListener("submit",async e=>{e.preventDefault();const q=input.value.trim();if(!q||send.disabled)return;input.value="";send.disabled=true;addMessage("user",q);if(!userId){addMessage("assistant","Fénix no pudo autenticarse. En Supabase, activa Authentication → Providers → Anonymous.");send.disabled=false;return}await saveMessage("user",q);const newMemory=rememberFrom(q);if(newMemory.length)await saveMemories(newMemory);const answer=generate(q);setTimeout(async()=>{addMessage("assistant",answer);await saveMessage("assistant",answer);send.disabled=false;input.focus()},220)});
input.addEventListener("input",()=>{input.style.height="auto";input.style.height=Math.min(input.scrollHeight,150)+"px"});boot();